# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process. 

# Site title and description
title:              Kount Docs
description:        Kount API and Platform Integration Guide.
lang:               en

# Site subpath, e.g. /blog
baseurl:            ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url:                "https://jarrettmitchell.github.io"

# Site logo # e.g. logo.png, upload logo image file to /uploads/ folder
logo:               "kountweblogo.svg" 

navbar:
    sticky:         true
    search:         true
  
# Default author settings
author:
    name:          
    title:         
    avatar:        

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
    Jarrett:
      name:         Jarrett Mitchell
      title:        Solutions Engineer     
      avatar:       avatar-jarrett.jpeg
    evan:
      name:          
      title:            
      avatar:       
    sara:
      name:         
      title:            
      avatar:       
    alex:
      name:       
      title:         
      avatar:      
    daniel:
      name:         
      title:           
      avatar:      
    tom:
      name:         
      title:           
      avatar:       

# Social icons displayed in footer
social:
    email: support@kount.com
    website: www.kount.com
    facebook:       
    flickr:
    dribbble:
    github: http://kount.github.io/
    googleplus:
    instagram:      
    linkedin:
    pinterest:
    twitter:       
    vimeo:          
    youtube:

# Share button
share:
    post:           true # Display share buttons on a post page
    doc:            false # Display share buttons on a doc page
    twitter:        false # Enable by adding Twitter handle 
    facebook:       false # Enable by setting true (Facebook handle not required)

# Default footer image settings
footer:
    copyright:      ©2019 Kount Inc. All Rights Reserved


# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      # 1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Number of posts displayed on blog page
paginate:           10

# Blog path
paginate_path:      "/blog/:num/"

# Path to post content assets directory i.e post images, pdfs etc
uploads:            /uploads/

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
  - jekyll-algolia
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  docs:
    output:         true
  faqs:
    output:         false
  changelogs:
    output:         false

algolia:
  application_id: ZFVDSFHNGJ
  index_name:     Kount Docs

# Defaults
defaults:
  # _posts
  - scope:
      path:         ""
      type:         posts
    values:
      layout:       post
  # _docs
  - scope:
      path:         ""
      type:         docs
    values:
      layout:       doc
